specVersion: 1.0.0
name: xc20-subql
version: 0.0.4
runner:
  node:
    name: '@subql/node'
    version: ^0.33.0
  query:
    name: '@subql/query'
    version: 0.24.0
description: Indexing of xc20 deposits, withdrawals and transfers
repository: 'https://github.com/parascan-xyz/xc20-subql'
schema:
  file: ./schema.graphql
network:
  chainId: '0x91bc6e169807aaa54802737e1c504b2577d4fafedd5a02c10293b1cd60e39527'
  endpoint: 'wss://moonbeam-alpha.api.onfinality.io/public-ws'
  dictionary: 'https://api.subquery.network/sq/subquery/moonbase-alpha-dictionary'
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleMint
          kind: substrate/EventHandler
          filter:
            module: assets
            method: Issued
        - handler: handleBurn
          kind: substrate/EventHandler
          filter:
            module: assets
            method: Burned
        - handler: handleTransfer
          kind: substrate/EventHandler
          filter:
            module: assets
            method: Transferred
