specVersion: 1.0.0
name: xc20-subql
version: 0.0.4

runner:
  node:
    name: '@subql/node'
    version: ^0.33.0
  query:
    name: '@subql/query'
    version: 0.24.0

description: Indexing of xc20 deposits, withdrawals and transfers
repository: 'https://github.com/parascan-xyz/xc20-subql'

schema:
  file: ./schema.graphql

network:
  chainId: '0x401a1f9dca3da46f5c4091016c8a2f26dcea05865116b286f60f668207d1474b'
  endpoint: 'wss://moonriver.api.onfinality.io/public-ws'
  dictionary: 'https://api.subquery.network/sq/subquery/moonriver-dictionary'

dataSources:
  - kind: substrate/Runtime
    startBlock: 1705944
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: xTokens
            method: TransferredMultiAssets
