specVersion: 1.0.0
name: subquery-starter
version: 0.0.4
runner:
  node:
    name: '@subql/node'
    version: ^0.33.0
  query:
    name: '@subql/query'
    version: 0.24.0
description: Tracker of xtoken deposit and withdrawals
repository: 'https://github.com/subquery/subql-starter'
schema:
  file: ./schema.graphql
network:
  chainId: '0x401a1f9dca3da46f5c4091016c8a2f26dcea05865116b286f60f668207d1474b'
  endpoint: 'wss://moonriver.api.onfinality.io/public-ws'
  dictionary: 'https://api.subquery.network/sq/subquery/moonriver-dictionary'
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: assets
            method: Issued
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: assets
            method: Transferred
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: assets
            method: Burned
